// Generated by scripts/build-photos.mjs — do not edit by hand.
export type PhotoKey = "dog-tui" | "dog-moana" | "dog-pip" | "dog-kiri" | "dog-honey" | "dog-nana" | "dog-bruno" | "dog-scruff" | "dog-sunny" | "dog-rangi" | "dog-jazz" | "dog-biscuit" | "cat-oreo" | "cat-maple" | "cat-tigger" | "cat-luna" | "cat-mr-fluff" | "cat-patches" | "cat-smokey" | "cat-pumpkin" | "cat-pebble" | "cat-salt-pepper" | "cat-kowhai" | "rabbit-clover" | "rabbit-snow" | "rabbit-duo" | "gp-duo" | "hero-hug" | "hero-friends" | "hero-cuddle" | "hero-lap-cat" | "hero-run" | "hero-cupcakes" | "hero-play" | "hero-pat" | "hero-bed" | "hero-kittens";
export type PhotoMeta = { width: number; height: number; alt: string; author: string; source: string; blur: string };
export const PHOTOS: Record<PhotoKey, PhotoMeta> = {
  "dog-tui": {
    "width": 1600,
    "height": 1067,
    "alt": "A tan, long-coated dog sitting by a wooden fence",
    "author": "Laula Co",
    "source": "https://unsplash.com/photos/ufPziMiRqU8",
    "blur": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAAAQAgCdASoMAAgAA4BaJQBOj+AC4pC7nYegAP6YDNNagG/mRM+2A9pVSCSyrtvIQaX69CSY+/NN+QBQCW/xgi9m6zQZieqodq4AunOkDQAAAA=="
  },
  "dog-moana": {
    "width": 1600,
    "height": 1280,
    "alt": "A brown dog with a red collar sitting indoors",
    "author": "Devin H",
    "source": "https://unsplash.com/photos/tGXl4gAvUwU",
    "blur": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADQAQCdASoMAAoAA4BaJQBOgB9SNRJgAAD+9vIzNxc7lRbXh0DxCstd9Z5aFW5ib0C0553CYb6kCp+KlhvWr8avlrAAAA=="
  },
  "dog-pip": {
    "width": 1600,
    "height": 1067,
    "alt": "A black and white border collie with a red collar outdoors",
    "author": "Katie Bernotsky",
    "source": "https://unsplash.com/photos/bP10_VqLnnw",
    "blur": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAACwAQCdASoMAAgAA4BaJYgAAfkdPQkAAP4FaOBD0oucHOWQu576w0kNLD9uUQj3eyYJzSThZ2rsRC96oMFV0TgzVBwAAA=="
  },
  "dog-kiri": {
    "width": 1600,
    "height": 1068,
    "alt": "A young tricolour dog looking up from the grass",
    "author": "Austin Kirk",
    "source": "https://unsplash.com/photos/QZenflkkwt0",
    "blur": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAADwAQCdASoMAAgAA4BaJZAC7ADhcT6OwwAA/s9zdtQaP4UJI64QYxtcRH3qx/Bb4fl1Qz4rTgC9eoHHTQ5cAA=="
  },
  "dog-honey": {
    "width": 1600,
    "height": 1067,
    "alt": "A golden puppy with a red collar looking to the side",
    "author": "Berkay Gumustekin",
    "source": "https://unsplash.com/photos/ngqyo2AYYnE",
    "blur": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAADwAQCdASoMAAgAA4BaJYgCdADdqewz7uAA/kE/QBG7F1pD6+3y5WqTNuN3uItspxR1fzMpKpewpa0tY+2QwsftTT1ZPyuqVUXJlCvQ9UhET6iudZtTf8CWAAA="
  },
  "dog-nana": {
    "width": 1600,
    "height": 1000,
    "alt": "An older golden dog resting its head on the floor",
    "author": "Linoleum Creative Collective",
    "source": "https://unsplash.com/photos/ZQu-3viOINA",
    "blur": "data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAAAQAgCdASoMAAcAA4BaJZQCdAD0mj8owqgAAP7uqlCimObc5TA16C+Y7wIcqKkNvlFCYKUe06RAAA=="
  },
  "dog-bruno": {
    "width": 1600,
    "height": 1060,
    "alt": "A large chocolate-brown dog with soft eyes",
    "author": "Michael",
    "source": "https://unsplash.com/photos/PVlnNm5RHSM",
    "blur": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAADwAQCdASoMAAgAA4BaJZQCdADhhP9bu4AA/gnls9pGA7dn3OjEBTJGbpzv8IOMfx23Kgv4wTiSUzCMF17CLIZo/vdSY2AA"
  },
  "dog-scruff": {
    "width": 1600,
    "height": 1068,
    "alt": "A scruffy black and grey dog lying on a blue sofa",
    "author": "Loren Cutler",
    "source": "https://unsplash.com/photos/-H5KIjcVxwI",
    "blur": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADQAQCdASoMAAgAA4BaJYwAAxdCmpommAD+7SET6lQHH6XYzSPr0LcMKaRUVC9/JelJE+g43D18wO+H25aGTqzANCQAAA=="
  },
  "dog-sunny": {
    "width": 1600,
    "height": 1067,
    "alt": "A cream Labrador smiling in a sunny field",
    "author": "Daniel Hering",
    "source": "https://unsplash.com/photos/0_ole_Z2pV8",
    "blur": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAAAQAgCdASoMAAgAA4BaJagCdAEegaSUwiYAAP5hbwn27n2yK5Mh7/PbTBYzHhz/bQtxkhGZRXCyZORfv6dENd3b/mKml5f62qLlpk30LAAAAA=="
  },
  "dog-rangi": {
    "width": 1600,
    "height": 1200,
    "alt": "A German shepherd lying in green grass",
    "author": "AcidFern",
    "source": "https://unsplash.com/photos/pbjcPSXUI2M",
    "blur": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADQAQCdASoMAAkAA4BaJZgCdADMiMhfQAD+Z0Xp/WqCaI7PHeqlCGiFAvyF04kA06dtyyJOFmysYD00ZKBh1srQr3uWqQBFICQAAA=="
  },
  "dog-jazz": {
    "width": 1600,
    "height": 1067,
    "alt": "A small black, white and tan dog against a pink wall",
    "author": "Victor G",
    "source": "https://unsplash.com/photos/N04FIfHhv_k",
    "blur": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADwAQCdASoMAAgAA4BaJQBOgCL9XudLEQAA/vBbE/bPzjsTHVq3gWcYVsFNQ/LvoQPHe2A5ruIT+H1ooRih4LZaKNAAAA=="
  },
  "dog-biscuit": {
    "width": 1600,
    "height": 1067,
    "alt": "A corgi puppy lying down with its tongue out",
    "author": "fatty corgi",
    "source": "https://unsplash.com/photos/1QsQRkxnU6I",
    "blur": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAADQAQCdASoMAAgAA4BaJZQCdAEO9sabAAD+9goTUEObXgjRPmvlYObKpYL+AAAA"
  },
  "cat-oreo": {
    "width": 1600,
    "height": 1067,
    "alt": "A fluffy black and white cat on a dark background",
    "author": "Paul Hanaoka",
    "source": "https://unsplash.com/photos/o6RbK3y7mK4",
    "blur": "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAADQAQCdASoMAAgAA4BaJZwAAl256DBPAAD++FZpr7E+HGEPad6DhHRvp2rflLYqkaMbQira4AA="
  },
  "cat-maple": {
    "width": 1600,
    "height": 1067,
    "alt": "A close-up of a tortoiseshell cat's face",
    "author": "Tatyana Eremina",
    "source": "https://unsplash.com/photos/cQDu1G6lmRM",
    "blur": "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAACwAQCdASoMAAgAA4BaJZwAAl0fhODgAP7zZUE3cMIHMiZNI9bvZVZnyHIvqvhLU8jqSpUd98mAgAAA"
  },
  "cat-tigger": {
    "width": 1600,
    "height": 1067,
    "alt": "A wide-eyed tabby cat",
    "author": "Anton Darius",
    "source": "https://unsplash.com/photos/fP3NaY3VUPM",
    "blur": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAADQAQCdASoMAAgAA4BaJQBOgCP8kqyfBgD+8W/a46pil2Ik/zlRXJwO70Gmnu7LJCFuXGp/kViVPTkW+uhZGuAA"
  },
  "cat-luna": {
    "width": 1600,
    "height": 1067,
    "alt": "A Siamese-cross cat with blue eyes lying down",
    "author": "Felix Mittermeier",
    "source": "https://unsplash.com/photos/X_rJfNo0CdQ",
    "blur": "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAACwAQCdASoMAAgAA4BaJZwAAlrkJJ+QAP70kcMIVj0XaGdk0THJiRFFZjvXOKsvI9t8Gp0tGl0A6shAAAA="
  },
  "cat-mr-fluff": {
    "width": 1600,
    "height": 1067,
    "alt": "A long-haired tabby cat relaxing outdoors",
    "author": "Bee Felten-Leidel",
    "source": "https://unsplash.com/photos/DkYlK2vyuZg",
    "blur": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADQAQCdASoMAAgAA4BaJYgCdADZodyQQAD+3aLrTPp390cGXtARVe2wLfb+f05jsm7TZN4dp1nXKtkDensZLfsJmqUirH9sSfkgAA=="
  },
  "cat-patches": {
    "width": 1600,
    "height": 1067,
    "alt": "A white, tan and black cat looking at the camera",
    "author": "Sandy Millar",
    "source": "https://unsplash.com/photos/DrfFgts5sUA",
    "blur": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAADwAQCdASoMAAgAA4BaJYwC7AD8LiDHicAA/u9HvxY/s5G1z6QkFcLnWBuKNzia9Aw33wOVpVxEukKGZfpmYH3wAAA="
  },
  "cat-smokey": {
    "width": 1600,
    "height": 918,
    "alt": "A grey cat asleep on someone's lap",
    "author": "Paul Stollery",
    "source": "https://unsplash.com/photos/0Y2jGnBKdEU",
    "blur": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAADQAQCdASoMAAcAA4BaJbACdADx2IjTAADiGPIeVXXqxnG5OGTileaefZRb+jgXxCs/FkNk2JCQpnxxYqKeXo+IGOBfj0QWYMe3GAAA"
  },
  "cat-pumpkin": {
    "width": 1600,
    "height": 1067,
    "alt": "An orange tabby kitten walking through grass",
    "author": "Andriyko Podilnyk",
    "source": "https://unsplash.com/photos/RCfi7vgJjUY",
    "blur": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADQAQCdASoMAAgAA4BaJbACdAD5dM+1gAD5XanlP9hiNSlWhUPOQ/835meEp5b5ufFYvld0mny2PdBJ2X98T1ZOOshNltUsKgAAAA=="
  },
  "cat-pebble": {
    "width": 1600,
    "height": 1173,
    "alt": "A small grey and white kitten on a bed",
    "author": "Kote Puerto",
    "source": "https://unsplash.com/photos/so5nsYDOdxw",
    "blur": "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAACwAQCdASoMAAkAA4BaJYwCdACRgv4AAP7n1xngc6VJq3ck9dEJXuBJUKGNEtlyK2MWetoElrufnigAAAA="
  },
  "cat-salt-pepper": {
    "width": 1600,
    "height": 1067,
    "alt": "Two tabby and white kittens cuddled in a basket",
    "author": "Amy Baugess",
    "source": "https://unsplash.com/photos/MNju0A6EeE0",
    "blur": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAAAQAgCdASoMAAgAA4BaJYgCdH8AE5Rel0kAAP7ojl0MKSFd3X53pu33Yw9nV+wZDFQ0cqBVcEhl720A1ZSfcLfGjlUzE6f2M4RPfNMAuaAAAA=="
  },
  "cat-kowhai": {
    "width": 1600,
    "height": 1227,
    "alt": "A brown tabby cat with green eyes",
    "author": "Lloyd Henneman",
    "source": "https://unsplash.com/photos/mBRfYA0dYYE",
    "blur": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAABwAQCdASoMAAkAA4BaJZQAAkcUoAD+a0w9xtxtAjNU/gPTs/vJmL6YWft7IIM+RlJr9weqVE+e6sBdp5jZe6UgAAA="
  },
  "rabbit-clover": {
    "width": 1600,
    "height": 1200,
    "alt": "A lop-eared fawn rabbit sitting on grass",
    "author": "Waranya Mooldee",
    "source": "https://unsplash.com/photos/Efj0HGPdPKs",
    "blur": "data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAACQAQCdASoMAAkAA4BaJYgCsACPXEAA/ppNZvMfU8WnnGceBngQOiXuUs38JYupCIW2KvlsEuAAAA=="
  },
  "rabbit-snow": {
    "width": 1600,
    "height": 1200,
    "alt": "A white rabbit on green grass",
    "author": "Pablo Martinez",
    "source": "https://unsplash.com/photos/AdagxtVKRWE",
    "blur": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAADwAQCdASoMAAkAA4BaJYgCsAEXtenKygAA/vSZj+3OU3Z02wnTjka0ne1pILI0BuL7xz5eFveij0Qxm02KTEE4nYtY4qOtxmAdTpe+4IYqF8AA"
  },
  "rabbit-duo": {
    "width": 1600,
    "height": 1067,
    "alt": "Two small rabbits snuggled together",
    "author": "Lorna Ladril",
    "source": "https://unsplash.com/photos/3MSQtgCvyWg",
    "blur": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAACQAQCdASoMAAgAA4BaJQBOgBsym7AA/A8URVhfAJefY6mcFaqvUfBc8A3Smwfrdfpzyk05FaY+r5w3EfrE1ujA8oNQCUVtAAA="
  },
  "gp-duo": {
    "width": 1600,
    "height": 1067,
    "alt": "Two guinea pigs sharing grated carrot",
    "author": "Bonnie Kittle",
    "source": "https://unsplash.com/photos/MUcxe_wDurE",
    "blur": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAADwAQCdASoMAAgAA4BaJbACdAELVydz/IAA/u+HOldjBJDe056jZzLAwtscdbyO6b4iugRE7RsbroqSMJPcmFdpwxtKVGjmhFfcv2Ekw/MIgnoAAAA="
  },
  "hero-hug": {
    "width": 1600,
    "height": 1143,
    "alt": "A woman hugging a happy black dog in a field",
    "author": "Wade Austin Ellis",
    "source": "https://unsplash.com/photos/FtuJIuBbUhI",
    "blur": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAAAQAgCdASoMAAkAA4BaJaACdAEXfMRO8fQAAP3EmkmeCk5U9fN5iqWaI11HHmXYYbDWnOhK0CrIjRyGfQ14aGgo4XpRIx4Qe/EJXle3CJKhZXIAAAA="
  },
  "hero-friends": {
    "width": 1600,
    "height": 941,
    "alt": "A white dog and a grey cat cuddling on the grass",
    "author": "Krista Mangulsone",
    "source": "https://unsplash.com/photos/9gz3wfHr65U",
    "blur": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAABQAgCdASoMAAcAA4BaJYwCdAYrT248IgD/fvgA/gezvoeemQL71qlkIYBKiDMMK7Rfgh/Li5i3FuJBeoE7/FDfFls24AAA"
  },
  "hero-cuddle": {
    "width": 1600,
    "height": 1067,
    "alt": "A woman laughing as she hugs a brown and white dog",
    "author": "Helena Lopes",
    "source": "https://unsplash.com/photos/WhBGINtjuwc",
    "blur": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADwAQCdASoMAAgAA4BaJQBOgB+FrluoP8AA/s99hnqp9eDXN/fvqD9S0sZbhUJLZjUKXrfEICtreuQpv9nHLcWdoJvtPWPyfukFZeWQ9YAAAA=="
  },
  "hero-lap-cat": {
    "width": 1600,
    "height": 1067,
    "alt": "An orange and white cat resting on someone's lap",
    "author": "Helena Lopes",
    "source": "https://unsplash.com/photos/ZpMkK7nji-w",
    "blur": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADQAQCdASoMAAgAA4BaJQBOgCKeGmv2wAD2KylXY3FDtvq7o7nnMwFoyI03sC08VERqNXNLLpvGiN3u6kbhXFv0aYaxU98RlOdFCH3ZriAAAA=="
  },
  "hero-run": {
    "width": 1600,
    "height": 1068,
    "alt": "Two small dogs running happily down a dirt road",
    "author": "Alvan Nee",
    "source": "https://unsplash.com/photos/T-0EW-SEbsE",
    "blur": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADwAQCdASoMAAgAA4BaJZACdADdb+7zTtAA4mcMF/xuBcguZQsJBc39ay5cWyuMgJjsg4vzlcWQvrnuWqQJbKQWkSAAAA=="
  },
  "hero-cupcakes": {
    "width": 1600,
    "height": 1067,
    "alt": "A row of cupcakes with teal icing and sprinkles",
    "author": "Brooke Lark",
    "source": "https://unsplash.com/photos/pGM4sjt_BdQ",
    "blur": "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAADwAQCdASoMAAgAA4BaJYwCdH8AFcK3cQAA/u4h+hwZZBCGhq3wB5MWjfh6fp3LXNiraAAA"
  },
  "hero-play": {
    "width": 1600,
    "height": 1067,
    "alt": "A smiling woman holding up a small dog outdoors",
    "author": "Manuel Meza",
    "source": "https://unsplash.com/photos/KvKop_a_EXw",
    "blur": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADQAQCdASoMAAgAA4BaJZgCdADbqzcogAD+quZDdEzL1p+zCBl3ZfSsiOHKSSIbFjaJTX2PBTjwnKwFCBpy3f6cDg8/D1iiGxsOCMm+vXwAAA=="
  },
  "hero-pat": {
    "width": 1600,
    "height": 1067,
    "alt": "A hand gently patting a scruffy grey dog",
    "author": "Simone Dalmeri",
    "source": "https://unsplash.com/photos/FUR242Eu_z4",
    "blur": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAADQAQCdASoMAAgAA4BaJYwCdADdazSLwAD+5tnp2WFQpWAZNA2h0PbMJtIImW7yY8fUMcDQGuyQ3eXD9CHb5B9884NzjsFQAAA="
  },
  "hero-bed": {
    "width": 1600,
    "height": 1200,
    "alt": "A dog curled up in a soft grey dog bed with a blanket",
    "author": "Jamie Street",
    "source": "https://unsplash.com/photos/s9Tf1eBDFqw",
    "blur": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADwAQCdASoMAAkAA4BaJaACdAEfUlcgcPAA4gaAsQpPgC9N5FKh4CCwwlF1yNg/u0GayTZIMyAfmdiHDxfjdYHBD6Zr6RdXKLAAAA=="
  },
  "hero-kittens": {
    "width": 1600,
    "height": 1306,
    "alt": "A basket full of kittens",
    "author": "The Lucky Neko",
    "source": "https://unsplash.com/photos/2JcixB1Ky3I",
    "blur": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAADQAQCdASoMAAoAA4BaJQBOgCF5hX1AAAD+9/EO6ShlOTefeSDlUoxn7GJTIl7oQncMeQcVlwDA8dgjai4H5zRiukqQBx73cCr+O1OG0pQ4BAAA"
  }
};
