// Downloads the openly licensed photos listed in scripts/photos.json from the
// Unsplash CDN and writes resized WebP variants to public/photos, plus a typed
// manifest (lib/photos.generated.ts) with dimensions and a tiny blur preview.
// Run with: npm run photos
import { readFile, writeFile, mkdir } from "node:fs/promises";
import sharp from "sharp";

export const WIDTHS = [256, 384, 640, 828, 1080, 1440];
const QUALITY = 62;
const list = JSON.parse(await readFile(new URL("./photos.json", import.meta.url)));
await mkdir("public/photos", { recursive: true });

const manifest = {};
for (const p of list) {
  const url = `https://images.unsplash.com/${p.src}?w=1600&q=85&fm=jpg`;
  const res = await fetch(url);
  if (!res.ok) throw new Error(`${p.key}: ${res.status}`);
  const buf = Buffer.from(await res.arrayBuffer());
  const img = sharp(buf).rotate();
  const meta = await img.metadata();
  for (const w of WIDTHS) {
    await sharp(buf).rotate().resize({ width: w, withoutEnlargement: true })
      .webp({ quality: QUALITY, effort: 6 })
      .toFile(`public/photos/${p.key}-${w}.webp`);
  }
  const blur = await sharp(buf).resize({ width: 12 }).webp({ quality: 40 }).toBuffer();
  manifest[p.key] = {
    width: meta.width,
    height: meta.height,
    alt: p.alt,
    author: p.author,
    source: `https://unsplash.com/photos/${p.page}`,
    blur: `data:image/webp;base64,${blur.toString("base64")}`,
  };
  console.log("✓", p.key);
}

const ts = `// Generated by scripts/build-photos.mjs — do not edit by hand.
export type PhotoKey = ${Object.keys(manifest).map((k) => JSON.stringify(k)).join(" | ")};
export type PhotoMeta = { width: number; height: number; alt: string; author: string; source: string; blur: string };
export const PHOTOS: Record<PhotoKey, PhotoMeta> = ${JSON.stringify(manifest, null, 2)};
`;
await writeFile("lib/photos.generated.ts", ts);
